# CI de Nível 01 - Disparo Manual através de clique

name: 'Execução Manual'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  e2e-tests:
    name: Execução dos testes e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e

  lint:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Executar Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: '(^\.git/|^node_modules/|^reports/)'
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
