# CI de Nível 01 - Disparo Manual através de clique

name: 'Execução Manual'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  e2e-tests:
    name: Execução dos testes e2e
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-noble

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install --frozen-lockfile

      - name: Executando testes e2e
        run: yarn run e2e --reporter=line
        timeout-minutes: 2

  lint:
    name: Super Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Executar Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_INCLUDE: '^(src|test|e2e|api|css|\.github/workflows)/'
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_YAML: true
