# CI de Nível 02 - Execução Agendada

# Nome da pipeline
name: 'Scheduled Execution'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho agendado = schedule

on:
  workflow_dispatch:
  schedule:
    # cronograma de execução
    # 1 - minuto, 2 - hora, 3 dia do mês, 4 - mês, 5 - dia da semana
    - cron: '*/6 * * * *'

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  e2e-tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-noble

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/AppData/Local/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # instalação das dependências
      - name: Instalando dependências
        run: yarn install --frozen-lockfile

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e
